### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by pepijnolivier** [hayeah/playing-cards-assets#1]
Hi there.

I know this repository is pretty old, but could you add a license to it?
MIT ?

You can just copy this text into a file called `LICENSE.MD`:
> https://opensource.org/licenses/MIT

This will help all of us use your repo knowing that we can use it for free !
Cheers !

**Comment by nawedx** [comment]
@hayeah I have made a [PR](https://github.com/hayeah/playing-cards-assets/pull/3) to add MIT license for the repo.
